#! /usr/bin/env python
# _*_ coding:utf-8 _*_

import re
from baseUserInfosql import orderinfosq
#from op.baseUserInfosql import Newuserinfo
defaultencoding = 'utf-8'

print("-----start userblock-----")
class oderhistoryuB(object):
    def __init__(self, _argument1):
        self.result = ''
        self.username = _argument1

    def orderinfo_all(self):
        result = orderinfosq()
        result = result.GetOrderinfo()
        self.result = result
print("-----end userblock-----")
