#!/usr/bin/env python
# -*- coding: utf-8 -*-

from linkage.op import orderBlock
import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
def orderhistory(user_name):
#    user = userBlock.orderInfo(user_name)
#    user.userInfo_username()
#    if user.user_exist:
#       print "正在为您查询历史订单情况\n"
#           user=userBlock.oderhistoryuB(user_name)
#     else:
#        print "您查询的用户不存在，请重新核对用户信息"
  user=orderBlock.oderhistoryuB(user_name)
  user.orderinfo_all()
