#! /usr/bin/env python
# _*_ coding:utf-8 _*_

import re
from linkage.op.baseUserInfosql import orderinfosq
defaultencoding = 'utf-8'
class oderhistoryuB(object):
    def __init__(self, _argument1):
        self.result = ''
        self.username = _argument1
   
    def orderinfo_all(self):
        result = orderinfosq(self.username)
        result = result.GetOrderinfo()
        self.result = result
        for item in result:  
          for value in item:
            print(value)
